spring.application.name=SafeCryptoStocksApplication

spring.jta.atomikos.datasource.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
spring.datasource.url=jdbc:mysql://localhost:3306/SafeCryptoStocksApplication
spring.datasource.username=root
spring.datasource.password=your mySql password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yours@gmail.com
spring.mail.password=irlo vljn lswg mxss
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com



logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.mail=DEBUG
logging.level.com.SafeCryptoStocks=DEBUG


spring.session.store-type=none

spring.security.user.name=admin
spring.security.user.password=admin@123

# Set session timeout to 30 minutes
server.servlet.session.timeout=30m

